### ISSUE TITLE
enable url end-point sharing (perhaps it needs to have a server?), include radio buttons to control randomization modes etc.

### ISSUE THREAD

**Issue by bjornregnell** [bjornregnell/muntabot#5]
@oliverlevay Currently the implementation is relying on the # hack to load two different "apps"...

But I'm thinking that this is one app and the page is a dynamic DOM so why not just update the DOM and changing the link to "All questions" and "Random questions" to a button that dynamically updates the DOM? Seems simpler and could be supported by the current Document module... What do you think? (I'm thinking this is a thing you want to do in a SPA, and this nice and simple `Document` module could help with that as a strat for a easy-to-use api for beginners...)

Another bonus, apart from being simpler, is that the URL willk not include strange # stuff...

**Comment by oliverlevay** [comment]
> @oliverlevay Currently the implementation is relying on the # hack to load two different "apps"...
> 
> But I'm thinking that this is one app and the page is a dynamic DOM so why not just update the DOM and changing the link to "All questions" and "Random questions" to a button that dynamically updates the DOM? Seems simpler and could be supported by the current Document module... What do you think? (I'm thinking this is a thing you want to do in a SPA, and this nice and simple `Document` module could help with that as a strat for a easy-to-use api for beginners...)
> 
> Another bonus, apart from being simpler, is that the URL willk not include strange # stuff...

The problem I was trying to solve is if a student is trying to send a link to a friend with the page that they're on or use the "back" button in the browser. That's why I used the hash to dictate where the user is going.

**Comment by bjornregnell** [comment]
Well, if it is just one url, then the back button leaves the app; but that's ok if the muntabot is shared using the single and only "canonical" url. Or am I missing something?

**Comment by oliverlevay** [comment]
> Well, if it is just one url, then the back button leaves the app; but that's ok if the muntabot is shared using the single and only "canonical" url. Or am I missing something?

Yes but what if a student wants to link the [https://fileadmin.cs.lth.se/pgk/muntabot/#rehearsal/category](https://fileadmin.cs.lth.se/pgk/muntabot/#rehearsal/category) ? But I agree with the `easy-of-use` argument and I can absolutely fix this if you want.

**Comment by bjornregnell** [comment]
> But I agree with the "easy-of-use" argument and I can absolutely fix this if you want.

Yes; although it works as is, this is more a way of simplifying both the code and the UI, so if you want to do it I'm happy to accept a PR, but i don't think it is "necessary". Could be interesting though to compare the code and see which version is simpler and more straight forward.

> this requires to add a "back" button manually (like the Slumpa frågor button) if this is not implemented there is no way to go back except reload the page.

Perhaps a radio button for this would be even more nice than a link or "back"-button enabled? Like     
`Slumpa frågor  [X----radio---O]  Alla frågor`
So the user can toggle. It's discoverable and might look nice... What do you think about that?

(I agree that this is about taking the philosophy of REST-ful URL-based pages or not, but I'd like to see how far we can take the single-page appphilosophy, where the code contains "it all" in one page and no "reload" or "back" is needed, by making it "feel" a bit like a "normal" desktop app. And it is not a big deal -- but interesting to investigate...)

//B

**Comment by oliverlevay** [comment]
> > But I agree with the "easy-of-use" argument and I can absolutely fix this if you want.
> 
> Yes; although it works as is, this is more a way of simplifying both the code and the UI, so if you want to do it I'm happy to accept a PR, but i don't think it is "necessary". Could be interesting though to compare the code and see which version is simpler and more straight forward.
> 
> > this requires to add a "back" button manually (like the Slumpa frågor button) if this is not implemented there is no way to go back except reload the page.
> 
> Perhaps a radio button for this would be even more nice than a link or "back"-button enabled? Like `Slumpa frågor [X----radio---O] Alla frågor` So the user can toggle. It's discoverable and might look nice... What do you think about that?
> 
> (I agree that this is about taking the philosophy of REST-ful URL-based pages or not, but I'd like to see how far we can take the single-page appphilosophy, where the code contains "it all" in one page and no "reload" or "back" is needed, by making it "feel" a bit like a "normal" desktop app. And it is not a big deal -- but interesting to investigate...)
> 
> //B

Seems interesting! I like the radio button idea. Expanding on this should be done as a library. I would love to work on this.

**Comment by bjornregnell** [comment]
won't fix as I want it to be a single page thing with no server. The "until week" feature is fixed here: https://github.com/bjornregnell/muntabot/commit/c7b23aefb2a0b25f0426a471ef3ce078bacd7424
using a simple text field
