### ISSUE TITLE
Specify the use of Option in one write code question

### ISSUE THREAD

**Issue by JohanbcEkberg** [bjornregnell/muntabot#9]
In question 
Week(7) -> Code("en funktion som linjärsöker efter en instans av klassen Person\nmed ett visst efternamn i en osorterad sekvens av personer\nmed hjälp av en while (och inte find/indexOf)")

src/main/scala/data.scala line 19.

Specify that the return type  should be Option since we can return None if sequence does not contain a Person with the correct name.

**Comment by bjornregnell** [comment]
PR welcome

**Comment by JohanbcEkberg** [comment]
#18 
Made a short PR for this issue
